#+setupfile: info/index-sos-header.setup
#+include: info/common-header.org
#+title:[[https://www.cs.cmu.edu/afs/cs/usr/wing/www/ct-japanese.pdf][ GTD]]
#+AUTHOR: 鈴木正幸，非常勤講師
* 情報元
- Getting Things Done - Wikipedia
  https://ja.wikipedia.org/wiki/Getting_Things_Done

- タスク整理の基本は、頭の中を書き出すこと！ 「GTD」を簡単図解｜＠人事
  ONLINE
  https://at-jinji.jp/blog/11001/

  GTD処理の流れ図 ーー 分りやすいかも
  https://cdn-atjinji.freetls.fastly.net/wp/wp-content/uploads/2017/10/0f6d84c32f5da39987d6923a9aed1c24.jpg

- GTD®とは - 日本唯一のGTD公式サイト。GTD Japan
  http://gtd-japan.jp/about


* 生産性アップの金字塔｢GTD｣の理念をおさらい

   2014.04.29

** Getting Things Done、あるいは｢GTD｣とは、

- what :: 物事を効率よく処理し、生産性を上げるためのシステムです。

- ｢しなければならないこと｣をする時間を短縮し、
- ｢やりたいこと｣をする時間を増やすことです。

- 生産性コンサルタントであるデビッド・アレン氏のベストセラー本のタイトルです。

** 簡単に言えば、GTDとは...

- ｢しなければならなこと｣の全体像がわかり、
- ｢次に何をするか｣を選びやすくなることです。

- すべてのToDoタスクを頭の外へ追い出し、
- システムへ移し入れる

｢GTDは複雑だ｣という評判もあるが
- 適切なやり方を知らないから

この記事では、GTDの基本理念を入門者にもわかりやすく解説します。

** GTDの5つのステップ

GTDはひとつの整理体系です。

厳密なルールがあるわけではありません。

GTDは｢しなければならないこと｣を収集、整理し、その中から重要なものを選
びだすメソッドを提供します。
GTDには基本となる｢5つステップ｣があります。

*** 収集 

     ToDoリスト、アイデア、日課などすべてを収集し、ノートに書き出します。
               
     そのタスクを実際にやる時がくるまで頭の中から追い出しておきます。

*** 明確化
     
     しなければならないことを明らかにします。

     - 実行可能なタスクに分解
               	
     - その場で片付けられるタスクがあったら、その場で片付けてください。

     - 誰かに任せられるタスクは、誰かに任せます。

     この作業をすることで、何をすべきか考える時間を減らし、実行する時
     間を増やせます。

*** 整理

     タスクをカテゴリーと優先度で整理します。

     - タスクごとに締め切り日を決め、リマインダーをセットします。

     - タスクの優先度は必ず決めておくこと。

     - この段階では、まだタスクの実行はしません。

*** 見直し

     ToDoリストを見直します。

     - ToDoタスクを見渡して、 ｢次にやるタスク｣を決めます。

     - どのタスクを選べばいいか悩むときは、タスクの分解が不十分なのか
       もしれません。もう一度｢明確化｣の手順を行ってください。

       すべてのタスクが実行可能なサイズに分解されていきます。

     また、定期的にToDoリストを見直し、どれだけ進捗したか、優先度に変
     更がないかをチェック、システムがうまく機能しているか判断してくだ
     さい。

*** 実行

     選んだタスクを実行します。

     - すべてのToDoタスクは優先度とカテゴリーで整理されており、どのタ
       スクをいつやるべきかわかっているはず。

     - また、タスクはすべて実行可能なサイズに分解されています。あとは
       実行するだけです。

以上がGTDの基本原則です。

まとめると、

- GTDは｢覚えておかねばならない｣ことすべてを頭の中から取り出し、
- システムへと移し替え、
- 整理し、
- 実行可能なタスクに分解する仕組みです。

ここまでしておけば、こんどToDoリストを見た時に、重要なタスクはどれか、
いまできるタスクはどれかがすぐに判断できます。つまり、｢何をすべきか｣や
｢どうやればいいか｣について考える時間を減らし、｢実行する｣時間を増やせる
わけです。

** どうやってGTDを始めるか？

*** ツールの選択

アイデアやToDoタスク、そのほか覚えておくべきことのすべてを収集・整理で
きるツールが必要です。

*** 定期的に見直す

やるべきことの全体像を常に把握しておくのが重要。

- 毎週、少し時間をとってToDoリスト全体を見直します。
- 最初は毎日やるとよいでしょう。

また、優先度を決めておけば、次にどのタスクをやるべきかで悩む必要もあり
ません。

基本的に、あるタスクが完了したら、ToDoリストをすばやくチェックし、重要
なタスクかつ今すぐできるタスクはどれかを調べ、とりかかるタスクを瞬時に
選び出すのが理想です。そしてそれを繰り返すのです。

*** ｢整理しすぎない｣ように気を配る

ToDoタスクをどう整理するかはあなた次第です。

ただし、整理のし過ぎは逆効果です。

- ToDoのカテゴリーが多すぎたり、
- 優先度が細かく分かれすぎていたり、
- ラベルやフラグが増えすぎていたら、

物事をシンプルにしてください。

**** 私はこうやっています

- 毎朝5分間を使って、
  - ToDoリストにその日にやるべきことすべてが書き込まれているかをチェッ
    クします。
  - また、すべてのタスクが大きすぎたり曖昧すぎたりせず、実行可能なステッ
    プに分解されているかを確認します。

- 週に一度、30分か1時間を使って、
  - ウィークリー・レビューを行います。
  - やる予定だったのにできなかったタスクをフォローしたり、
  - 漠然としていたアイデアをToDoリストに加えたり、
  - 人に任せられるタスクを誰かに任せたり、
  - 小さなブレインストーミングを行ったり、
  - 優先度を見直します。

** GTDは基本理念のひとつにすぎない

GTDは素晴らしいメソッドですが、｢基本理念のひとつ｣に過ぎないことを忘れ
ないでください。

あなたとってベストな生産性システムではない可能性もあります。


* Getting Things Done Wikipedia
   SCHEDULED: <2015-12-30 水>
   
   [[/wiki/%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC][ワークフロー]] 管理手法
   [[/wiki/%E3%83%8F%E3%83%83%E3%82%AB%E3%83%BC%E6%96%87%E5%8C%96][ハッカー文化]]の一つで、*[[/wiki/LifeHack][LifeHack]]*（ライフハック）の中でも代表的なものである。

** GTDの特徴

- 仕事の優先順位をつけることを強調しない。

- 状況に応じたタスクリストを作る

- 新しい仕事が飛び込んできた場合、2分以内でできるようなものならばすぐ済
  ませるべきだとも説いている。

- 仕事すべてがリストに書き出され把握できているのでない状態で考えた優先
  順位はむしろ不正確であまり役に立たない。

GTDは、やらなければならない仕事に関する情報を蓄え、追跡し、思い出すこ
とを、簡単にするにはどうすればよいかという心理学的基礎に基づいている。

アレンは、ある活動を行う際にわれわれがぶつかる「心理的障害」の多くは、
非効率な「[[/wiki/%E3%83%95%E3%83%AD%E3%83%B3%E3%83%88%E3%82%A8%E3%83%B3%E3%83%89][フロント＝エンド]]」式計画（例えば、どんなプロジェクトでも、何
を達成すべきか、そのためには何をすべきかを、情報収集してまず最初に明ら
かにしなければならない）のために引き起こされるという。彼によればもっと
も実際的な方法は、まず何をしてどこまで達成すべきかを全部考え、そのあと
一連の行動を計画なしで自動的に行うことだという。

またアレンは、われわれの頭や心理にある「思い出すシステム」は非効率で、
その時その場所ですべきことを思い出すことはめったにないという。よって、
「信頼できるシステム」の文脈にしたがって、すべき仕事を紙や電子機器に書
き出して蓄積した「次の行動リスト」はわれわれの心を外側から支援する役割
を果たし、われわれが正しいときに正しいことを思い出すことを確実にしてく
れる。アレンによって説明されるGTDには、仕事の流れを円滑にする助けとな
る個人の仕事管理のコツや方法が詳述されている。

何よりGTDで求められるのは、[[/wiki/%E4%BB%95%E4%BA%8B][仕事]]・[[/wiki/%E3%83%93%E3%82%B8%E3%83%8D%E3%82%B9][ビジネス]]を遂行する上で行わなければな
らない作業を明確化し、それを逐次処理で貫徹することにある。例えば途中経
過で失敗した場合、その後のスケジュールが総崩れを起こすのは良くない傾向
である。これを予防する上で、先回りしてリカバリーポイント（失地回復の場）
を要所要所に設け、スケジュール管理することなどが挙げられる。

** システム

GTDは次の5つのステップで構成され、これを1週間など一区切りごとに繰り返す

1. 収集 :: 

   頭の中にある「やらなければならないこと」「気になっていること（問題）」
           を紙などに書き出す。作業中のメモ書きなども参照して、問題点
           を出していく。
2. 処理 ::

   書き出した内容を、手順に添って、分類しリスト化する。

3. 整理:: 

   リストを自身がスケジュール管理に使っている[[/wiki/%E3%83%84%E3%83%BC%E3%83%AB][ツール]]（[[/wiki/%E6%90%BA%E5%B8%AF%E6%83%85%E5%A0%B1%E7%AB%AF%E6%9C%AB][PDA]]や[[/wiki/%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E6%89%8B%E5%B8%B3][シス
   テム手帳]]など）に入れ込む。

4. 見直し :: 

   自分の状況や状態でそれらが可能かどうか見直し、検討する。

5. 実行 :: 

   リストアップした「出来ること」を順次片付ける。

こういった作業を行うための手順の見直しをステップを追って行うことで、
「あれもしなくちゃいけないし、これもやらなきゃいけないし...」といった
混乱した状況から脱して、着実に作業を進めて行くのがGTDである。こういっ
た手法は、一見仕事が連続した作業の繰り返しで「ここからここまでが1単位」
という見通しがなかなか立て難い状況で役立つとされている。

*** 収集
     
**** バケットの中に集める

      - 追いかけなければならない仕事
      - 覚えておくべき仕事
      - 取り掛かっている途中の仕事（公私問わず）
      
      をすべて残らず書き出し、集める。

**** バケット
      紙、メモ帳、PDA、パソコン、現実の整理箱やパソコン画面上の電子メー
      ルの整理箱

      すべき仕事に関する雑然とした想念を頭から全部追い出す

**** バケットの整理

      中身は、週に最低一度は整理して空にする必要がある。


*** 処理

     書き出してバケットに投げ込んだ仕事を分類し、厳密な[[/wiki/%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC][ワークフロー]]によっ
     て各リストへと分ける作業である。

     - まず整理箱のトップやメモ用紙などの最初にある仕事から「処理」をはじめる。
     - 処理する仕事は一度に一個だけ。
     - 整理箱には絶対にどんな仕事も戻さない。
     - 処理の開始。整理箱にあるその仕事は、行動をおこすべきものかどうか、
       考えることが処理の内容である。

       - *YES。行動すべき*
         - すぐやる。（2分以内でできる場合）
         - 複雑なものは、計画を立てて行うことにし、計画は定期的に見直す。
           *プロジェクト*のリストへ。
         - 複雑でないもので、自分でしなくてもいいものは人に任せる。任せ
           たら *連絡待ち* のリストへ。
         - 複雑ではないが今すぐしなくてもよいものは後でする。*カレンダー*のリストへ。
         - 複雑ではなく今すぐしたほうがよいものは、今やっている仕事の次に着手する。
           *次のアクション*のリストへ。

       - *NO。今行動しなくてよい*
         - 資料としてファイルにしまうものは、*資料*リストへ。
         - いつかやる仕事としてあたためておくものは、*いつかする*リストへ。
         - 不要なものは捨てて忘れる。ゴミ箱へ。

     この処理の際に、「するのに2分とかからない仕事は、今すぐ行う」とい
     う「*2分ルール*」がある。「2分」とは目安で、その仕事を後へ延ばすた
     めにリストやメモを書いたりするのにかかる時間くらいのことである。2
     分くらいでできそうな細かい仕事は、いまこの場でリストから早めに消し
     てすっきりさせる必要がある。


*** 整理

     残っている仕事に常に注意を払うために使う「リスト」には、以下のよう
     なものがある。バケットにある仕事は処理によってこの「リスト」へ仕分
     けされ、このリストを常時追跡しながら仕事をこなしてゆく。

     - 次のアクション :: 注意をしなければならない仕事それぞれについて、
                         取るべき次のアクション（その仕事の最初の一歩）
                         は何かを決める。

          たとえば、もし仕事が「プロジェクトレポートを書く」ならば、次
          のアクションは「Aさんにミーティングの時間について電子メールを
          打つ」か、「Bさんに電話してレポートに必要な内容を聞く」などと
          なる。仕事完了までにこなすステップや行動はいろいろあるが、そ
          の最初にすべきことは必ずあるはずで、これを「次のアクション」
          リストに入れ、今やっている仕事の次から次へと行う。さらにこれ
          らは起こす行動の状況に応じて分類したほうがよい。例えば、「オ
          フィスでする」「電話する」「店でする」など。

     -  プロジェクト :: プライベートや仕事での「オープン・ループ」の中
          で、一回以上の物理的動作が必要な、複雑な仕事は「プロジェクト」
          になる。これらは常に追跡し、定期的に見直す。プロジェクトに関
          する「次のアクション」は後回しになり、随時進めていく。

     -  連絡待ち :: 誰かに仕事や「次のアクション」を任せる場合、あるい
          はプロジェクトを進めるにあたり何か外部の出来事が起こるのを待
          たねばならない場合、これらは追跡できる状態にし、随時任せた仕
          事が終わったか、外部で出来事が起きたか、見直すこととする。

     -  いつかやる :: いつかやりたいが今しなくていいものはここに入れる。
          「将来に備え中国語を勉強」「ダイビングのために休暇をとる」な
          ど。

     -  カレンダー :: カレンダーも約束や仕事の追跡のために重要である。
          しかし、アレンは、カレンダーは「ハード・ランドスケープ」と彼
          が名づけた仕事のためにとっておくべきだと勧めている。ハード・
          ランドスケープは、ある決まった締め切りまでに絶対にすべき仕事
          や、時間や場所が決まってしまった会議や約束のことである。すべ
          き仕事はカレンダーではなく、次のアクションリストに書かれるべ
          きである。

     GTDの鍵になるものはファイリングシステムである。ファイリングは簡単
     で、単純で、楽しく苦痛にならないシステムでなければならない。紙1枚
     に書いたものでも、見直すために必要なら、これまで作ったフォルダに属
     さないものならば新しいフォルダを作る必要がある。アレンの推薦するも
     のはアルファベット順の単純なファイリングシステムであるが、情報の貯
     蔵や見直しができるだけ簡単で早く済むものならどういったものでもよい。


*** 見直し

     「43Folders」の例

     アクションや覚えておくべきもののリストは、毎日や毎週あるいは随時な
     ど、見直すことがなければ役に立たない。リストを見直して、やり忘れて
     いるものがあればすぐ着手したほうがよい。またある特定の時点で十分な
     時間とエネルギーがある場合、リストの中から何が今もっともすべきこと
     かを決定し、すぐやるほうがよい。ただし、ぐずぐず先延ばししがちな人
     ならば、リストの中の簡単なものから手をつけて後に大変なものが残りが
     ちである。この解決のためには、リストの上から機械的に順番に着手する
     ようにしたほうがいい。

     GTDでは、最低週に一度、残っているアクションやプロジェクト、連絡待
     ちなどの仕事の進捗や要不要を評価し、新しく入った仕事や次に来る出来
     事などを次々収集・処理・整理してリストに加え、常に新しい状態にしな
     ければならない。

     アレンは「備忘録」をつくり、毎週頭の中から仕事やプロジェクトの記憶
     をすっきり整理してしまうことを勧めている。これは12か月分と31日分の
     43個のフォルダからなるもので、毎日その日の日付のフォルダを開けて仕
     事をこなして空にし、空になったフォルダは次の月のフォルダの中に入れ
     るというものである。


*** 実行

     どのようなリストやシステムも、それを作ることばかりに時間をかけ、実
     際の仕事を行わないようでは意味がない。以上の方法で頭をすっきりさせ、
     とらなければならないアクションをとることを、簡単に、単純に、楽しい
     ものにできた場合、先伸ばししがちな傾向は少なくなり、「オープン・ルー
     プ」のあまりの多さに圧倒されてげんなりすることも少なくなるであろう。


* アメリカ人が選ぶ！ 生産性アップのテクニック・ベスト5

   http://www.lifehacker.jp/2012/05/120514productivityfive.html

** Pomodoroテクニック

25分にセットしたタイマーを動かすと同時に仕事を始めます。そしてこの25分
間は仕事に集中し、その間は途中で仕事を止めてはいけません。

そしてタイマーが鳴ったら5分間の休憩をとります。

このセットを繰り返し、4セット目ごとに15分から30分の長めに休憩します。

より短時間で効果的に集中することができるでしょう。

** [[http://www.lifehacker.jp/cat3/gtd/][Getting Things Done]]

GTDの本質は、*あなたのタスクやアイデアを頭の中から出してすぐに整理して、
把握や管理をしやすくすることです*。

GTDが勧めるのは、タスクを優先順位順
に従い「*すぐに片付けられるものはすぐに終わらせ、手間のかかるものは分
けて早く終わるものから先に処理する*」こと。

** Don't Break the Chain

[[http://lifehacker.com/5886128/how-seinfelds-productivity-secret-fixed-my-procrastination-problem][Seinfeldの生産性をアップするテクニック（Don'tBreak the Chain）]]大切なこ
とを続けるため」や「目標を達成するため」に、自然の流れに沿って簡単に実
行できる方法です。

[[http://dontbreakthechain.com/][実践したいことをカレンダーに記入して色をつけていくだけ]]。
そうすれば、そのことを持続するモチベーションが上がります。この一
連の流れを崩してはいけません。このテクニックを始めるのに必要なものは*
カレンダーとペンのみ*です。カレンダーを見れば、どれだけ続けてそれを行っ
ているかが一目瞭然です。Adam氏が[[http://lifehacker.com/5886128/how-seinfelds-productivity-secret-fixed-my-procrastination-proble][彼自身の記事]]で「このテクニックは休みの
日の計画を立てる要領でモチベーションを上げることができる方法なのだ」と
語っています。

** [[http://www.actionmethod.com/][アクション・メソッド]]

   http://www.actionmethod.com/

このテクニックの目的は、

「あなたのタスクを完了するために必要なすべての作業（アクション・ステッ
プ）」を会議やアイデア提案の場などでまとまった形にして示すことです*。

すべてのアクションステップにはタスクが付帯します。そしてそれらは「リファ
レンス」や「アクション・ステップ」とは区別します。なかには、このように
タスクをすべてまとめてしまうことやカテゴリを取り払ってしまう方法が嫌い
な方もいるでしょう。しかし、この方法によりタスクがスッキリし、いつでも
実行できる「アクション・アイテム」を小分けすることができます。Action
Methodは、Behance/iOS/Androidなど向けのアプリ、もしくは紙ベースの
『[[http://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=Action+Journal][Action Journal]]』や『[[http://www.amazon.com/Action-Runner-Blue-by-Behance/dp/B001C0W7RG/ref=sr_1_1?ie=UTF8&qid=1337062044&sr=8-1][ActionRunner]]』
でも実践できます。



