# coding:utf-8
# coding:utf-8
require 'date'
require 'rake/clean'

def myhome
  path = `pwd`.chomp.split("/").reverse
  depth = path.index("org")
  [depth+1, path[0..depth].reverse]
end

def org_sub_dir
  if File.exist?("Rakefile.setup.rb")
    puts "loading Rakefile.setup.rb."
    load "./Rakefile.setup.rb"
    SUBDIRS
  else
    (Dir.glob("*/*.org").map do |f| File.dirname(f) end).uniq
  end
end

if File.exist?("Rakefile.setup.rb")
  puts "loading Rakefile.setup.rb."
  load "./Rakefile.setup.rb"
else
  SUBDIRS = org_sub_dir
  EXCLUDES = FileList ["Makefile.org", "Rakefile.org", "log.org", "0*.org"]
  ORGS = FileList["*.org"] - EXCLUDES
  HTMLS = ORGS.ext(".html")
end

NOW = DateTime.now.to_s

puts "HTMLS: #{HTMLS}"
puts "SUBDIRS: #{SUBDIRS}"

CLEAN.include(FileList["*~","#*"])
CLOBBER.include(HTMLS)

ORGS.each do |org|
  html = File.basename(org, ".org")+".html"
  @depends = `~/COMM/bin/org_dependency.rb #{org}`.chomp.gsub(' ','').split(",")
  if @depends.size!=0 
    file html => @depends.push(org) do |t|
      sh "~/COMM/bin/org2html #{org}"
      deploy(t.name, "#{SITE}/#{DIR}")
    end
  end
end

  
depth,path = myhome

MYHOME = "../"*depth
ORG = "#{MYHOME}org/"
SITE = "#{MYHOME}docs/"
path.shift
DIR = path.join("/")
DOCSHOME = "../"*(depth-1)

def deploy(file, dir)
  p "deploying #{dir}#{file}"
  sh "mkdir -p #{dir}"
  File.open("#{dir}/#{file}", "w") do |target| 
    all = File.read(file).gsub("http:\/\/", "https:\/\/")
    all.gsub!("https:\/\/www.pirilampo.org", DOCSHOME+".")
    all.gsub!("https:\/\/wiki.cis.iwate-u.ac.jp\/~suzuki\/org-html-theme", DOCSHOME+".")
    all.gsub!("\/\/orgmode.org\/mathjax\/MathJax.js", "\/\/cdn.mathjax.org\/mathjax\/latest\/MathJax.js?config=TeX-MML-AM_CHTML")
    target.write(all)
  end

  sh "git add #{dir}/#{file}"
  sh "git commit -m deploy_#{NOW} #{dir}/#{file}"

end


rule ".html" => ".org" do |t|
  sh "~/COMM/bin/org2html #{t.prerequisites.join(' ')}"
  deploy(t.name, "#{SITE}/#{DIR}")
end

def compile_latex(file, dir)
  p "latex_compile #{file}"
  sh "mv #{file} working/"
  sh "cd working/; make"
  sh "git add #{dir}/#{file}"
  sh "git commit -m deploy_#{NOW} #{dir}/#{file}"

end


rule ".tex" => ".org" do |t|
  sh "~/COMM/bin/org2latex #{t.prerequisites.join(' ')}"
  latex_compile(t.name, "#{SITE}/#{DIR}")
end

task :default => [:org2html]

task :org2html => HTMLS do
  puts "git push"
  sh "git push"
end

task :deploy => HTMLS do |t|
  (t.prerequisites).each do |h|
    deploy(h, "#{SITE}/#{DIR}")
  end
end

task :subdirs do
  org_sub_dir.each do |subdir|
    Dir.chdir(subdir) do
      puts `pwd`
      sh "rake"
    end
  end
end    

task :subdirs_install_rakefile do
  org_sub_dir.each do |subdir|
    Dir.chdir(subdir) do
      puts `pwd`
      sh "cp ../Rakefile.org ."
      sh "cp ../Rakefile ."
      sh "rake subdirs_install_rakefile"
    end
  end
end
