* 成功する人の「9のストレス対処法」

 Heidi Grant Halvorson博士は米・コロンビア大学で「モチベーション」を
 テーマに研究する心理学者です。著書『Nine Things Successful People
 Do Differently（成功する人が実践する9つの行動）』をもち、

 違うのは、ストレスを感じた時の対処法なのです。

 科学的に効果が証明されたストレス対処法を9つ紹介

** 自分の失敗を受け入れる姿勢を持つ

   何かミスや失敗をしても、それを受け入れる姿勢を持つことが大切です。

   研究によると、失敗を受け入れる姿勢を持っている人は幸せで、楽観的で、
   心配事が少なく、より成功しやすいことがわかっています。

   多くの人は「自分に厳しい人ほどパフォーマンスが上がって成功しやすい」
   と思っていますが、全く正しくありません。

   自分の失敗を受け入れる人は「失敗から学ぶ姿勢」を持っているため、大
   変な時でもストレスを減らしてパフォーマンスを上げられるのです。人間
   はミスをするのが当たり前です。くれぐれも、自分を責めないように心が
   けましょう。

** 抽象化して考える

   どんなことでも考え方はひとつではありません。例えば、「運動する」は
   抽象化して考えると「健康になる」と言い換えられます（逆に具体化して
   考えると「2km走る」となります）。同じように、どれほど小さな行動でも、
   抽象化すれば「大きな意味や目的」が見えてきます。仕事で遅くまで残業
   している時は、「つまらないメール処理に追われている」と考えるより
   「キャリアのために頑張っている」と考える方がモチベーションを維持し
   やすいのです。

** 習慣化する

   ストレスの大きな原因は「決定することが多いから」なのです。
    
   毎日起こる小さな問題に無駄な時間を取られないようにしないといけない。

   大切なのは、決定に使うエネルギーを本当に重要な問題だけに使うことで
   す。そのために習慣化が必要なのです。

** 興味があることをする

   最新の研究によると、人間は興味のあることをしていると疲れないだけで
   なく、逆に活力が湧いてくるというのです。湧いてきた活力は、さらに次
   の行動に使えるでしょう。

   ただ、2つの重要なポイントを理解しておく必要があります。

   - まず、「興味がある」は「おもしろい」とは違います。
   - また、「楽しい」や「うれしい」とも違います。

   例として、友達と昼ご飯を食べるとします。

   - 一緒に食べれば「楽しい」し、会話は「おもしろい」かもしれません。
   - 料理の味が良ければ「うれしい」 でしょう。
   - しかし、話題の分子調理法を取り入れた料理を食べない限り「興味があ
     る」とは言えないのです。

   「興味がある状態」を正確に理解する必要があります。
      
   また、仕事で難しいタスクに取り組んでいる場合でも、「興味がある」
   部分を意識することで、疲れやストレスが溜まりにくくなることもわかっ
   ています。

   日々の仕事でも、興味が持てる要素を探してみましょう。興味が持てれば、
   仕事の質を落とさずにペースを維持できます。

** ToDoリストに期限や場所を追加する

   ToDoリストを使っていますか？　使っている場合、書き出した項目が片付
   かずに何週間も経ってしまうことはないでしょうか。答えがイエスなら、
   ストレスが溜まるはずです。ToDoの項目をできるだけ早く片付けるには
   「条件付き実行計画（If-then planning）」が効果的です。

   条件付き実行計画とは、計画の際に期限や場所も一緒に決めることで、目
   標を達成するのに強い効果があります。ささいなことだと思うかもしれま
   せんが、この分野において数百もの研究が発表されています。条件付き実
   行計画を用いると、2倍から3倍も達成する確率が高まることがわかってい
   ます。

   ToDoリストにも明確な期日と場所を追加しましょう。例えば、「ボブに電
   話する」という項目は「火曜日の午後2時になったらボブに電話する」とな
   ります。このように予定を立てると、私たちの脳は無意識のうちに「火曜
   日の午後2時」という状況を描き出します。もし、忙しい時でも、この状況
   はしっかり頭の中に残っているため、実際に予定を達成する可能性が高ま
   るのです。


** ポジティブな独り言をつぶやく

   ポジティブな独り言をつぶやくのも、ストレスと戦う方法です。これだけ
   で、ストレスを感じる体験からポジティブな反応が引き出せるようになり
   ます。

   例えば、
   
   - 「受信ボックスに大量のメールが入っていたら、落ち着いて穏やかな気
     分になる」とか、
   - 「締め切りが近づいたら、頭を冷やす」

   ストレスを感じる体験と自分が望む反応をセットにしてつぶやいてみましょ
   う。

   最新の研究によると、このような独り言を事前に繰り返すことで、感情的
   な反応（恐れ、悲しみ、疲れ、自己不信、嫌悪感など）をある程度コント
   ロールできることがわかっています。

** 「完璧マインド」ではなく、「改善マインド」を持つ

   完璧マインドとは「すでに持っている多くの知識やスキル
   をいかに証明するか」であり、

   改善マインドは「足りない知識やスキルをいかに改善するか」です。

   「完璧マインド」を持っている人は、
   - 最初からすべてのことを完璧にこなせると考えているため、
   - 無意識のうちに自分と他人を比べています。
   - 何か物事がうまくいかないと、すぐに自分の能力を疑い、不安やストレス
     を感じ始めます。
   - 皮肉なことに、自分の能力を疑えば疑うほど、最終的に失敗しやすくなるのです。

   「改善マインド」を持っている人は、
   - 今の自分が過去の自分と比較して改 善しているかどうかを重要視します。
   - 成長する過程でのミスや失敗は仕方がないとわかっているため、感じる
     ストレスはずっと少なく、モチベーションを高く維持できます。

** 小さな前進を意識する

   心理学者のTeresa Amabile氏とSteven Kramer氏は著書『Progress
   Principle（前進の法則）』で、「仕事で適切な精神状態を保つために最も
   重要なのは、常に前進している状態を保つこと」と述べています。心理学
   的に言うと、私たちの感情は現在地点から目標地点までの進み具合によっ
   て決まります。残っている課題に目を向ける前に、一息入れてこれまでに
   達成したことを振り返りましょう。着実に前進していることがわかれば、
   気分はずっと前向きになるはずです。
 
** ポジティブ思考に効果がない人もいると理解する
 
   ポジティブ思考が大事なのはわかっていても、仕事が大変な時はなかなか
   実践できないものです。それでいて、いつでも簡単にポジティブ思考がで
   きる人もいます。実際のところ、それは全くおかしいことではありません。
   モチベーションをテーマにした研究によると、ポジティブ思考に効果がな
   い人もいることがわかったのです。
 
   自分の仕事について、「目標や希望を達成する機会」と考える人と、「義
   務や責任を果たす機会」と考える人がいます。心理学の世界では前者を
   「促進フォーカス」と呼び、後者を「予防フォーカス」と呼びます。促進
   フォーカスとは、経済学的に言えば「機会を逃さずに利益を最大化するこ
   と」です。反対に、予防フォーカスは「現状を守って損失を最小化するこ
   と」です。同じ目標を目指す場合でも、人によって促進フォーカスを使う
   人もいれば、予防フォーカスを使う人もいるのです。
 
   促進フォーカスは「これがしたい！」といった熱意のようなもので、楽観
   主義によって支えられています。逆に言うと、「すべてうまくいく」と信
   じなければ促進フォーカス的な行動はできないのです。反対に、予防フォー
   カスは「これをしなくて大丈夫か？」といった警戒心のようなもので、不
   安をバネに努力しようとします。これは、テストで失敗するのを恐れて勉
   強する学生と似ています。…


