:PROPERTIES:
:ID:       26014c0a-cb29-4f16-a4ea-77ab720a86b1
:END:
#+title: finite-element-simulation
Altair University
[[https://altairuniversity.com/ebook-fea-jp/ebook-fea-jp-excerpt/][数値解法の種類（有限要素法（FEM）・境界要素法・有限体積法・有限差分法） - Altair University]]

* 数値解法の種類（有限要素法（FEM）・境界要素法・有限体積法・有限差分法）

** 1. 有限要素法（FEM）

- 最も一般的な数値的解法です。

- 有限要素法 （FEM）とは、偏微分方程式 （PDE）の定義域 （W）の近似解を
  求めるときに使用する数値的解法です。PDEを解くときの最大の難関は、解
  を近似的に表す基底関数を作る工程です。基底関数の作り方は数多くありま
  すが、どれを使用するかは選択した定式化によって決まります。
  
- 線形 / 非線形 / 座屈 / 熱 / 動的 / 疲労解析で使用できます。

** 2. 境界要素法（BEM）

- 境界要素法（BEM）は、音響やNVHの問題を非常に強力に、かつ効率よく解く
  ことができる解法です。
- 有限要素法と同様に節点と要素を用いますが、その名のとおり、対象領域の
  境界についてのみ考えます。そのため、たとえば立体の問題の場合は外側の
  表面しか考慮せず、領域が平面の場合は外縁しか考慮しません。このように
  次元を1つ減らすことにより、問題を素早く解くことができます。
- 境界要素法 （BEM）は、線形偏微分方程式を定式化した積分方程式を解く数値的解法です。
- この積分方程式は、支配偏微分方程式の厳密解と見なせる場合もあります。
  BEMでは、偏微分方程式によって定義された領域のすべての値を求めるので
  はなく、与えられた境界条件を用いて境界値を積分方程式に近似することを
  試みます。この積分方程式は、解析後のポストプロセスの段階で、解析領域
  内の任意点の解を数値的に計算するために再利用することもできます。BEM
  は一般的に、比表面積が小さい問題を、有限要素法などの解法よりも少ない
  計算リソースで効率よく解くことができます （BEMは、モデルの表面にかけ
  た“メッシュ（網）”を解くイメージです）。ただし多くの問題では、FDM、
  FVM、FEMなどの体積離散化解法よりも効率の面で大きく劣ります。

** 3. 有限体積法（FVM）

- 有限体積法 （FVM）は、偏微分方程式を代数方程式で表現し、評価するため
  の解法です（LeVeque, 2002; Toro, 1999）。
- 一般的な形状を離散化した空間で値を計算するFDMと非常によく似ています。
  FVMでは、発散項を含む偏微分方程式の体積積分を、発散定理を用いて表面
  積分に変換します。その後それらの項を、各有限体積の表面の流束として評
  価します。任意の体積に流入する流束は、隣接する体積から流出する流束と
  等しいことから、有限体積法は保存的な解法と言えます。有限体積法のもう
  1つの長所は、非構造格子を扱うための定式化が容易な点です。FVMは多くの
  数値流体力学パッケージで使用されています。

** 4. 有限差分法（FDM）

- 有限要素法と共通点の多い解法です。有限差分法 （FDM）は、一般的に微分
  方程式を解く解法と言われています。テイラー級数を用いて微分方程式を代
  数方程式に変換しますが、変換時、次数の高い項は無視されます。FDMは、
  熱-CFD連成問題を解くためにBEMやFVMと組み合わせて使用されます。

- ＊FEM、BEM、FVMは積分方程式を離散化しますが、FDMは偏微分方程式を離散化します。


** [[https://www.hulinks.co.jp/support/flexpde/intro.html][偏微分方程式ソルバ [FlexPDE] | ヒューリンクス]]

- FlexPDE は米国 PDE Solutions (http://www.pdesolutions.com/) のソフト
  ウエア製品で、偏微分方程式と条件を指定するだけで、解が得られます。通
  常、所与の偏微分方程式群を差分法あるいは有限要素法を用いて、近似式に
  展開し、これをプログラミングする必要がありますが、FlexPDEは有限要素
  法による展開を自動的に実行して、解を出してくれる偏微分方程式の汎用ソ
  ルバーです。

- 近似式への展開は最も時間もかかり、神経を使うところで、大抵のバグは、
  展開式の間違いに起因することを考えますと、所与の式を数式処理によって
  展開し、解を出してくれる機能は大変便利です。問題を解く立場からすれば、
  これが非常に理想的であることは言うまでもありません。

- 市場には、数式処理ソフト、偏微分方程式を解くツールは各種ありますが、
  この両者を一体化したツールは、FlexPDE が唯一ではないかと思います。

- FlexPDE は別に偏微分方程式のみに特化しているわけではなく、これ以外の
  方程式とその n 次微分あるいは偏微分についても扱うことができますが、
  有限要素法がいずれの場合でも内部で適用されています。
